# Generated by Django 2.2.6 on 2019-12-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=32)),
                ('course_price', models.IntegerField()),
                ('course_teacher', models.CharField(max_length=16)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=16)),
                ('student_id', models.IntegerField()),
                ('student_phone', models.IntegerField()),
                ('student_address', models.CharField(max_length=128)),
            ],
        ),
    ]
