# Generated by Django 2.2.6 on 2019-12-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_permissionsmanagement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
